const words = [
  "Adventure",
  "Anvil",
  "Arcade",
  "Balloon",
  "Beach",
  "Beacon",
  "Bedrock",
  "BedWars",
  "Bicycle",
  "Biome",
  "Bird",
  "Blaze",
  "BlazePowder",
  "BlazeRod",
  "BlazeSpawner",
  "Blitz",
  "Blossom",
  "Boat",
  "Brilliant",
  "Cake",
  "Captivate",
  "Cascade",
  "Catacombs",
  "Cave",
  "Champion",
  "Cloud",
  "Cobblestone",
  "CocoaBeans",
  "Coins",
  "Crafting",
  "CraftingTable",
  "Creeper",
  "CreeperFarm",
  "Crypt",
  "Dance",
  "Daydream",
  "Delicate",
  "DesertTemple",
  "Diamond",
  "DiamondArmor",
  "DiamondAxe",
  "DiamondOre",
  "DiamondShovel",
  "DiamondSword",
  "Dragon",
  "Dungeon",
  "Elephant",
  "Elytra",
  "Emerald",
  "EmeraldOre",
  "EnchantedBook",
  "Enchanting",
  "EnchantingTable",
  "Enchantment",
  "EnderArmor",
  "EnderChest",
  "EnderCrystal",
  "EnderDragon",
  "Enderman",
  "Endermite",
  "EnderPearl",
  "EndStone",
  "Fantasy",
  "Farming",
  "Fjord",
  "Flower",
  "Fortress",
  "Fox",
  "Frog",
  "FrozenBlaze",
  "FrozenScythe",
  "Ghast",
  "Glimmer",
  "Glitter",
  "Glow",
  "GoldenApple",
  "GoldenCarrot",
  "GoldIngot",
  "Goldor",
  "GrapplingHook",
  "Grass",
  "Guardian",
  "Guitar",
  "Gypsy",
  "Happy",
  "Harmony",
  "HayBale",
  "Housing",
  "Hunt",
  "Hypixel",
  "IronArmor",
  "IronGolem",
  "IronIngot",
  "IronPickaxe",
  "Jigsaw",
  "Journey",
  "Jump",
  "Jungle",
  "JungleTemple",
  "JungleWood",
  "LapisLazuli",
  "Laughter",
  "LavaBucket",
  "LeapingSword",
  "Lobby",
  "Magic",
  "MagmaCube",
  "Majestic",
  "Mana",
  "Marathon",
  "Mastiff",
  "Maxor",
  "Melody",
  "Memento",
  "Midas",
  "Milk",
  "Minecart",
  "Minion",
  "Mnemonic",
  "Mountain",
  "Moxie",
  "Music",
  "Mystery",
  "Necron",
  "Nether",
  "NetherBrick",
  "NetherFortress",
  "Netherite",
  "NetherPortal",
  "NetherQuartz",
  "NetherStar",
  "NetherWart",
  "Network",
  "Obsidian",
  "Ocean",
  "OceanMonument",
  "Octopus",
  "Overflux",
  "Pencil",
  "Penguin",
  "PumpkinPie",
  "Puzzle",
  "Queue",
  "Quirk",
  "Quiz",
  "Rabbit",
  "Rainbow",
  "Ranked",
  "Redstone",
  "RedstoneBlock",
  "RedstoneDust",
  "RedstoneLamp",
  "RedstoneTorch",
  "Revenant",
  "Rhythm",
  "Runaan",
  "Scorpion",
  "Silverfish",
  "Skeleton",
  "SkyBlock",
  "SkyWars",
  "Slayer",
  "SlimeBlock",
  "Smile",
  "Sparkle",
  "Spawner",
  "Sphinx",
  "Steve",
  "StoneBricks",
  "Storm",
  "Strong",
  "Stronghold",
  "SugarCane",
  "Sunny",
  "Sunrise",
  "Sunshine",
  "Survival",
  "Sven",
  "Sweet",
  "Symphony",
  "Tarantula",
  "TNTGames",
  "Train",
  "Treasure",
  "Twilight",
  "Vex",
  "Villager",
  "Vortex",
  "Watermelon",
  "Whisper",
  "Wise",
  "Wither",
  "WoodenSword",
  "Wrath",
  "Yacht",
  "Yeti",
  "Zealot",
  "Zombie",
  "ZombiePigman",
];

function getRandomWord(length = undefined) {
  length = undefined;
  if (length !== undefined) {
    const filteredWords = words.filter((word) => word.length == length);

    if (filteredWords.length === 0) {
      // eslint-disable-next-line no-throw-literal
      throw `No words found with the ${length} characters.`;
    }

    return filteredWords[Math.floor(Math.random() * filteredWords.length)];
  } else {
    return words[Math.floor(Math.random() * words.length)];
  }
}

function scrambleWord(word) {
  const chars = word.split("");

  for (let i = chars.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [chars[i], chars[j]] = [chars[j], chars[i]];
  }

  return word === chars.join("") ? scrambleWord(word) : chars.join("");
}

module.exports = { getRandomWord, scrambleWord };
