module.exports = {
    talismans: {
        wedding_ring_0: { rarity: 'common' },
        wedding_ring_2: { rarity: 'uncommon' },
        wedding_ring_4: { rarity: 'rare' },
        wedding_ring_7: { rarity: 'epic' },
        wedding_ring_9: { rarity: 'legendary' },

        campfire_talisman_1: { rarity: 'common' },
        campfire_talisman_4: { rarity: 'uncommon' },
        campfire_talisman_8: { rarity: 'rare' },
        campfire_talisman_13: { rarity: 'epic' },
        campfire_talisman_21: { rarity: 'legendary' },

        farming_talisman: {},
        vaccine_talisman: { rarity: 'common' },
        wood_talisman: { rarity: 'uncommon' },
        skeleton_talisman: {},
        coin_talisman: { rarity: 'common' },
        magnetic_talisman: {},
        gravity_talisman: {},
        village_talisman: {},
        mine_talisman: {},
        night_vision_charm: {},
        lava_talisman: {},
        scavenger_talisman: {},
        fire_talisman: {},
        piggy_bank: {},
        cracked_piggy_bank: {},
        broken_piggy_bank: {},
        pigs_foot: {},
        wolf_paw: {},
        frozen_chicken: {},
        fish_affinity_talisman: {},
        farmer_orb: {},
        haste_ring: {},
        experience_artifact: {},
        new_year_cake_bag: {},
        day_crystal: { rarity: 'rare' },
        night_crystal: { rarity: 'rare' },
        feather_talisman: {},
        feather_ring: {},
        feather_artifact: {},
        potion_affinity_talisman: {},
        ring_potion_affinity: {},
        artifact_potion_affinity: {},
        healing_talisman: {},
        healing_ring: {},
        candy_talisman: {},
        candy_ring: {},
        candy_artifact: {},
        melody_hair: { rarity: 'epic' },
        sea_creature_talisman: { rarity: 'common' },
        sea_creature_ring: {},
        sea_creature_artifact: {},
        intimidation_talisman: {},
        intimidation_ring: {},
        intimidation_artifact: {},
        wolf_talisman: {},
        wolf_ring: {},
        bat_talisman: {},
        bat_ring: {},
        bat_artifact: {},
        devour_ring: {},
        zombie_talisman: {},
        zombie_ring: {},
        zombie_artifact: {},
        spider_talisman: {},
        spider_ring: {},
        spider_artifact: {},
        ender_artifact: {},
        tarantula_talisman: {},
        survivor_cube: {},
        wither_artifact: {},
        red_claw_talisman: {},
        red_claw_ring: {},
        red_claw_artifact: {},
        bait_ring: {},
        shady_ring: {},
        crooked_artifact: {},
        seal_of_the_family: {},
        hunter_talisman: {},
        hunter_ring: {},
        party_hat_crab: {},
        potato_talisman: {},
        emerald_ring: { rarity: 'uncommon' },
        personal_compactor_4000: { rarity: 'uncommon' },
        personal_compactor_5000: { rarity: 'rare' },
        personal_compactor_6000: { rarity: 'epic' },
        personal_compactor_7000: { rarity: 'legendary' },
        personal_deletor_4000: { rarity: 'uncommon' },
        personal_deletor_5000: { rarity: 'rare' },
        personal_deletor_6000: { rarity: 'epic' },
        personal_deletor_7000: { rarity: 'legendary' },
        speed_talisman: { rarity: 'common' },
        speed_ring: { rarity: 'uncommon' },
        speed_artifact: { rarity: 'rare' },
        cat_talisman: { rarity: 'uncommon' },
        lynx_talisman: { rarity: 'rare' },
        cheetah_talisman: { rarity: 'epic' },
        scarf_studies: { rarity: 'rare' },
        scarf_thesis: { rarity: 'epic' },
        scarf_grimoire: { rarity: 'legendary' },
        treasure_talisman: { rarity: 'rare' },
        treasure_ring: { rarity: 'epic' },
        treasure_artifact: { rarity: 'legendary' },
        mineral_talisman: { rarity: 'rare' },
        beastmaster_crest_common: { rarity: 'common' },
        beastmaster_crest_uncommon: { rarity: 'uncommon' },
        beastmaster_crest_rare: { rarity: 'rare' },
        beastmaster_crest_epic: { rarity: 'epic' },
        beastmaster_crest_legendary: { rarity: 'legendary' },
        raggedy_shark_tooth_necklace: { rarity: 'common' },
        dull_shark_tooth_necklace: { rarity: 'uncommon' },
        honed_shark_tooth_necklace: { rarity: 'rare' },
        sharp_shark_tooth_necklace: { rarity: 'epic' },
        razor_sharp_shark_tooth_necklace: { rarity: 'legendary' },
        hegemony_artifact: { rarity: 'legendary' },
        bits_talisman: { rarity: 'rare' },
        bat_person_talisman: { rarity: 'common' },
        bat_person_ring: { rarity: 'uncommon' },
        bat_person_artifact: { rarity: 'rare' },
        candy_relic: { rarity: 'legendary' },
        lucky_hoof: {},
        eternal_hoof: {},
        wither_relic: { rarity: 'legendary' },
        catacombs_expert_ring: { rarity: 'epic' },
        auto_recombobulator: { rarity: 'legendary' },
        jerry_talisman_green: { rarity: 'uncommon' },
        jerry_talisman_blue: { rarity: 'rare' },
        jerry_talisman_purple: { rarity: 'epic' },
        jerry_talisman_golden: { rarity: 'legendary' },
        king_talisman: { rarity: 'common' },
        titanium_talisman: { rarity: 'uncommon' },
        titanium_ring: { rarity: 'rare' },
        titanium_artifact: { rarity: 'epic' },
        titanium_relic: { rarity: 'legendary' },
        reaper_orb: { rarity: 'legendary' },
        dante_talisman: { rarity: 'common' },
        spiked_atrocity: { rarity: 'epic' },
        blood_god_crest: { rarity: 'common' },
        master_skull_tier_1: { rarity: 'common' },
        master_skull_tier_2: { rarity: 'common' },
        master_skull_tier_3: { rarity: 'uncommon' },
        master_skull_tier_4: { rarity: 'uncommon' },
        master_skull_tier_5: { rarity: 'rare' },
        master_skull_tier_6: { rarity: 'epic' },
        master_skull_tier_7: { rarity: 'legendary' },
        soulflow_pile: { rarity: 'uncommon' },
        soulflow_battery: { rarity: 'rare' },
        soulflow_supercell: { rarity: 'epic' },
        pocket_espresso_machine: { rarity: 'common' },
        handy_blood_chalice: { rarity: 'common' },
        ender_relic: { rarity: 'legendary' },
        jungle_amulet: { rarity: 'uncommon' },
        power_talisman: { rarity: 'common' },
        power_ring: { rarity: 'uncommon' },
        power_artifact: { rarity: 'rare' },
        nether_artifact: { rarity: 'epic' },
        burststopper_talisman: { rarity: 'rare' },
        burststopper_artifact: { rarity: 'epic' },
        fiery_kuudra_core: { rarity: 'epic' },
        burning_kuudra_core: { rarity: 'rare' },
        infernal_kuudra_core: { rarity: 'rare' },
        jacobus_register: { rarity: 'legendary' },
        odgers_bronze_tooth: { rarity: 'common' },
        odgers_silver_tooth: { rarity: 'uncommon' },
        odgers_gold_tooth: { rarity: 'rare' },
        odgers_diamond_tooth: { rarity: 'epic' },
        pulse_ring: { rarity: 'uncommon' },
        blaze_talisman: { rarity: 'rare' },
        netherrack_looking_sunshade: { rarity: 'common' },
    },
};
