// credit: https://github.com/SkyCryptWebsite/SkyCrypt/blob/b9842bea6f1494fa2d2fd005b64f57d84646c188/src/constants/forge.js#L1 (Modified)
module.exports = {
  // Times in mins
  items: {
    // Old Items (Before mining v3)
    REFINED_DIAMOND: { name: "Refined Diamond", time: 480 },
    REFINED_MITHRIL: { name: "Refined Mithril", time: 360 },
    REFINED_TITANIUM: { name: "Refined Titanium", time: 720 },
    FUEL_TANK: { name: "Fuel Tank", time: 600 },
    BEJEWELED_HANDLE: { name: "Bejeweled Handle", time: 30 },
    DRILL_ENGINE: { name: "Drill Engine", time: 1800 },
    GOLDEN_PLATE: { name: "Golden Plate", time: 360 },
    MITHRIL_PLATE: { name: "Mithril Plate", time: 1080 },
    GEMSTONE_MIXTURE: { name: "Gemstone Mixture", time: 240 },
    PERFECT_JASPER_GEM: { name: "Perfect Jasper Gemstone", time: 1200 },
    PERFECT_RUBY_GEM: { name: "Perfect Ruby Gemstone", time: 1200 },
    PERFECT_JADE_GEM: { name: "Perfect Jade Gemstone", time: 1200 },
    PERFECT_SAPPHIRE_GEM: { name: "Perfect Sapphire Gemstone", time: 1200 },
    PERFECT_AMBER_GEM: { name: "Perfect Amber Gemstone", time: 1200 },
    PERFECT_TOPAZ_GEM: { name: "Perfect Topaz Gemstone", time: 1200 },
    PERFECT_AMETHYST_GEM: { name: "Perfect Amethyst Gemstone", time: 1200 },
    PERFECT_OPAL_GEM: { name: "Perfect Opal Gemstone", time: 1200 },
    BEACON_2: { name: "Beacon II", time: 1200 },
    BEACON_3: { name: "Beacon III", time: 1800 },
    BEACON_4: { name: "Beacon IV", time: 2400 },
    BEACON_5: { name: "Beacon V", time: 3000 },
    TITANIUM_TALISMAN: { name: "Titanium Talisman", time: 840 },
    TITANIUM_RING: { name: "Titanium Ring", time: 1200 },
    TITANIUM_ARTIFACT: { name: "Titanium Artifact", time: 2160 },
    TITANIUM_RELIC: { name: "Titanium Relic", time: 4320 },
    TITANIUM_DRILL_1: { name: "Titanium Drill DR-X355", time: 3840 },
    TITANIUM_DRILL_2: { name: "Titanium Drill DR-X455", time: 0.5 },
    TITANIUM_DRILL_3: { name: "Titanium Drill DR-X555", time: 0.5 },
    TITANIUM_DRILL_4: { name: "Titanium Drill DR-X655", time: 0.5 },
    MITHRIL_DRILL_1: { name: "Mithril Drill SX-R226", time: 240 },
    MITHRIL_DRILL_2: { name: "Mithril Drill SX-R326", time: 0.5 },
    MITHRIL_PICKAXE: { name: "Mithril Pickaxe", time: 45 },
    POWER_CRYSTAL: { name: "Power Crystal", time: 120 },
    REFINED_MITHRIL_PICKAXE: { name: "Refined Mithril Pickaxe", time: 1320 },
    MITHRIL_FUEL_TANK: { name: "Mithril-Infused Fuel Tank", time: 600 },
    MITHRIL_DRILL_ENGINE: { name: "Mithril-Plated Drill Engine", time: 900 },
    PURE_MITHRIL: { name: "Pure Mithril", time: 720 },
    ROCK_GEMSTONE: { name: "Rock Gemstone", time: 1320 },
    PETRIFIED_STARFALL: { name: "Petrified Starfall", time: 840 },
    GOBLIN_OMELETTE: { name: "Goblin Omelette", time: 1080 },
    GOBLIN_OMELETTE_PESTO: { name: "Pesto Goblin Omelette", time: 1200 },
    GOBLIN_OMELETTE_SUNNY_SIDE: { name: "Sunny Side Goblin Omelette", time: 1200 },
    GOBLIN_OMELETTE_SPICY: { name: "Spicy Goblin Omelette", time: 1200 },
    GOBLIN_OMELETTE_BLUE_CHEESE: { name: "Blue Cheese Goblin Omelette", time: 1200 },
    GEMSTONE_DRILL_1: { name: "Ruby Drill TX-15", time: 60 },
    GEMSTONE_DRILL_2: { name: "Gemstone Drill LT-522", time: 0.5 },
    GEMSTONE_DRILL_3: { name: "Topaz Drill KGR-12", time: 0.5 },
    GEMSTONE_DRILL_4: { name: "Jasper Drill X", time: 0.5 },
    HOT_STUFF: { name: "Hot Stuff", time: 1440 },
    AMBER_MATERIAL: { name: "Amber Material", time: 420 },
    TITANIUM_FUEL_TANK: { name: "Titanium-Infused Fuel Tank", time: 1500 },
    TITANIUM_DRILL_ENGINE: { name: "Titanium-Plated Drill Engine", time: 1800 },
    GEMSTONE_CHAMBER: { name: "Gemstone Chamber", time: 240 },
    RUBY_POLISHED_DRILL_ENGINE: { name: "Ruby-polished Drill Engine", time: 1200 },
    GEMSTONE_FUEL_TANK: { name: "Gemstone Fuel Tank", time: 1800 },
    PERFECTLY_CUT_FUEL_TANK: { name: "Perfectly-Cut Fuel Tank", time: 3000 },
    SAPPHIRE_POLISHED_DRILL_ENGINE: { name: "Sapphire-polished Drill Engine", time: 1800 },
    AMBER_POLISHED_DRILL_ENGINE: { name: "Amber-polished Drill Engine", time: 3000 },
    DIVAN_HELMET: { name: "Helmet of Divan", time: 1380 },
    DIVAN_CHESTPLATE: { name: "Chestplate of Divan", time: 1380 },
    DIVAN_LEGGINGS: { name: "Leggings of Divan", time: 1380 },
    DIVAN_BOOTS: { name: "Boots of Divan", time: 1380 },
    DIVAN_DRILL: { name: "Divan's Drill", time: 3600 },
    PET: { name: "[Lvl 1] Ammonite", time: 17280 },
    FORGE_TRAVEL_SCROLL: { name: "Travel Scroll to the Dwarven Forge", time: 300 },
    CRYSTAL_HOLLOWS_TRAVEL_SCROLL: { name: "Travel Scroll to the Crystal Hollows", time: 600 },
    DIAMONITE: { name: "Diamonite", time: 360 },

    // New Items (Mining v3)
    PERFECT_ONYX_GEM: { name: "Perfect Onyx Gemstone", time: 1200 },
    PERFECT_CITRINE_GEM: { name: "Perfect Citrine Gemstone", time: 1200 },
    PERFECT_AQUAMARINE_GEM: { name: "Perfect Aquamarine Gemstone", time: 1200 },
    PERFECT_PERIDOT_GEM: { name: "Perfect Peridot Gemstone", time: 1200 },
    BEJEWELED_COLLAR: { name: "Bejeweled Collar", time: 120 },
    CHISEL: { name: "Chisel", time: 0.5 },
    BASE_CAMP_TRAVEL_SCROLL: { name: "Travel Scroll to the Dawrven Base Camp", time: 600 },
    SECRET_RAILROAD_PASS: { name: "Secret Railroad Pass", time: 0.5 },
    DWARVEN_HANDWARMERS: { name: "Dwarven Handwarmers", time: 0.5 },
    DWARVEN_METAL: { name: "Dwarven Metal Talisman", time: 1440 },
    PORTABLE_CAMPFIRE: { name: "Portable Campfire", time: 30 },
    REFINED_TUNGSTEN: { name: "Refined Tungsten", time: 360 },
    REFINED_UMBER: { name: "Refined Umber", time: 360 },
    MOLE: { name: "[Lvl 1] Mole", time: 4320 },
    TYRANNOSAURUS: { name: "[Lvl 1] T-Rex", time: 7200 },
    SPINOSAURUS: { name: "[Lvl 1] Spinosaurus", time: 7200 },
    GOBLIN: { name: "[Lvl 1] Goblin", time: 7200 },
    ANKYLOSAURUS: { name: "[Lvl 1] Ankylosaurus", time: 7200 },
    PENGUIN: { name: "[Lvl 1] Penguin", time: 7200 },
    MAMMOTH: { name: "[Lvl 1] Mammoth", time: 7200 },
    SKELETON_KEY: { name: "Skeleton Key", time: 30 },
    UMBER_PLATE: { name: "Umber Plate", time: 120 },
    TUNGSTEN_PLATE: { name: "Tungsten Plate", time: 120 },
    PERFECT_PLATE: { name: "Perfect Plate", time: 30 },
    REINFORCED_CHISEL: { name: "Refined Chisel", time: 720 },
    GLACITE_CHISEL: { name: "Glacite Chisel", time: 1080 },
    TUNGSTEN_KEYCHAIN: { name: "Tungsten Keychain", time: 360 },
    GLACITE_AMALGAMATION: { name: "Glacite Amalgamation", time: 240 },
    FRIGID_HUSK: { name: "Frigid Husk", time: 600 },
    POWER_RELIC: { name: "Relic Of Power", time: 480 },
    UMBER_KEY: { name: "Umber Key", time: 30 },
    TUNGSTEN_KEY: { name: "Tungsten Key", time: 30 },
  },
  quickForgeMultiplier: {
    1: 0.895,
    2: 0.89,
    3: 0.885,
    4: 0.88,
    5: 0.875,
    6: 0.87,
    7: 0.865,
    8: 0.86,
    9: 0.855,
    10: 0.85,
    11: 0.845,
    12: 0.84,
    13: 0.835,
    14: 0.83,
    15: 0.825,
    16: 0.82,
    17: 0.815,
    18: 0.81,
    19: 0.805,
    20: 0.7,
  },
};
