// CREDIT: https://github.com/SkyCryptWebsite/SkyCrypt/ (Modified)

const symbols = {
  health: {
    name: "Health",
    nameLore: "Health",
    nameShort: "Health",
    nameTiny: "HP",
    symbol: "❤",
    suffix: "",
    color: "c",
  },
  defense: {
    name: "Defense",
    nameLore: "Defense",
    nameShort: "Defense",
    nameTiny: "Def",
    symbol: "❈",
    suffix: "",
    color: "a",
  },
  strength: {
    name: "Strength",
    nameLore: "Strength",
    nameShort: "Strength",
    nameTiny: "Str",
    symbol: "❁",
    suffix: "",
    color: "c",
  },
  intelligence: {
    name: "Intelligence",
    nameLore: "Intelligence",
    nameShort: "Intelligence",
    nameTiny: "Int",
    symbol: "✎",
    suffix: "",
    color: "b",
  },
  speed: {
    name: "Speed",
    nameLore: "Speed",
    nameShort: "Speed",
    nameTiny: "Spd",
    symbol: "✦",
    suffix: "",
    color: "f",
  },
  crit_chance: {
    name: "Crit Chance",
    nameLore: "Crit Chance",
    nameShort: "Crit Chance",
    nameTiny: "CC",
    symbol: "☣",
    suffix: "%",
    color: "9",
  },
  crit_damage: {
    name: "Crit Damage",
    nameLore: "Crit Damage",
    nameShort: "Crit Damage",
    nameTiny: "CD",
    symbol: "☠",
    suffix: "%",
    color: "9",
  },
  bonus_attack_speed: {
    name: "Bonus Attack Speed",
    nameLore: "Bonus Attack Speed",
    nameShort: "Attack Speed",
    nameTiny: "AS",
    symbol: "⚔",
    suffix: "%",
    color: "e",
  },
  ability_damage: {
    name: "Ability Damage",
    nameLore: "Ability Damage",
    nameShort: "Ability Damage",
    nameTiny: "AD",
    symbol: "๑",
    suffix: "%",
    color: "c",
  },
  true_defense: {
    name: "True Defense",
    nameLore: "True Defense",
    nameShort: "True Defense",
    nameTiny: "TDef",
    symbol: "❂",
    suffix: "",
    color: "f",
  },
  ferocity: {
    name: "Ferocity",
    nameLore: "Ferocity",
    nameShort: "Ferocity",
    nameTiny: "Fer",
    symbol: "⫽",
    suffix: "",
    color: "c",
  },
  magic_find: {
    name: "Magic Find",
    nameLore: "Magic Find",
    nameShort: "Magic Find",
    nameTiny: "MF",
    symbol: "✯",
    suffix: "",
    color: "b",
  },
  pet_luck: {
    name: "Pet Luck",
    nameLore: "Pet Luck",
    nameShort: "Pet Luck",
    nameTiny: "PL",
    symbol: "♣",
    suffix: "",
    color: "d",
  },
  sea_creature_chance: {
    name: "Sea Creature Chance",
    nameLore: "Sea Creature Chance",
    nameShort: "SC Chance",
    nameTiny: "SCC",
    symbol: "α",
    suffix: "%",
    color: "3",
  },
  fishing_speed: {
    name: "Fishing Speed",
    nameLore: "Fishing Speed",
    nameShort: "Fishing Speed",
    nameTiny: "FS",
    symbol: "☂",
    suffix: "",
    color: "b",
  },
  mining_speed: {
    name: "Mining Speed",
    nameLore: "Mining Speed",
    nameShort: "Mining Speed",
    nameTiny: "MngSpd",
    symbol: "⸕",
    suffix: "",
    color: "6",
  },
  mining_fortune: {
    name: "Mining Fortune",
    nameLore: "Mining Fortune",
    nameShort: "Mining Fortune",
    nameTiny: "MngFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  farming_fortune: {
    name: "Farming Fortune",
    nameLore: "Farming Fortune",
    nameShort: "Farming Fortune",
    nameTiny: "FrmFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  foraging_fortune: {
    name: "Foraging Fortune",
    nameLore: "Foraging Fortune",
    nameShort: "Foraging Fortune",
    nameTiny: "FrgFrt",
    symbol: "☘",
    suffix: "",
    color: "6",
  },
  pristine: {
    name: "Pristine",
    nameLore: "Pristine",
    nameShort: "Pristine",
    nameTiny: "Prs",
    symbol: "✧",
    suffix: "",
    color: "5",
  },
  damage: {
    name: "Damage",
    nameLore: "Damage",
    nameShort: "Damage",
    nameTiny: "Dmg",
    symbol: "❁",
    suffix: "",
    color: "c",
  },
  soulflow: {
    name: "Soulflow",
    nameLore: "Soulflow",
    nameShort: "Soulflow",
    nameTiny: "Sf",
    symbol: "⸎",
    suffix: "",
    color: "3",
  },
  overflow_mana: {
    name: "Overflow Mana",
    nameLore: "Overflow Mana",
    nameShort: "Overflow Mana",
    nameTiny: "OMn",
    symbol: "ʬ",
    suffix: "",
    color: "3",
  },
  heat: {
    name: "Heat",
    nameLore: "Heat",
    nameShort: "Heat",
    nameTiny: "Ht",
    symbol: "♨",
    suffix: "",
    color: "c",
  },
  absorption: {
    name: "Absorption",
    nameLore: "Absorption",
    nameShort: "Absorption",
    nameTiny: "Abs",
    symbol: "❤",
    suffix: "",
    color: "6",
  },
  breaking_power: {
    name: "Breaking Power",
    nameLore: "Breaking Power",
    nameShort: "Breaking Power",
    nameTiny: "BP",
    symbol: "Ⓟ",
    suffix: "",
    color: "2",
  },
  health_regen: {
    name: "Health Regen",
    nameLore: "Health Regen",
    nameShort: "Health Regen",
    nameTiny: "HPR",
    symbol: "❣",
    suffix: "",
    color: "c",
  },
  vitality: {
    name: "Vitality",
    nameLore: "Vitality",
    nameShort: "Vitality",
    nameTiny: "Vit",
    symbol: "♨",
    suffix: "",
    color: "5",
  },
  mending: {
    name: "Mending",
    nameLore: "Mending",
    nameShort: "Mending",
    nameTiny: "Mend",
    symbol: "☄",
    suffix: "",
    color: "a",
  },
  wisdom: {
    name: "Wisdom",
    nameLore: "Wisdom",
    nameShort: "Wisdom",
    nameTiny: "W",
    symbol: "☯",
    suffix: "",
    color: "3",
  },
  rift_time: {
    name: "Rift Time",
    nameLore: "Rift Time",
    nameShort: "Rift Time",
    nameTiny: "RT",
    symbol: "ф",
    suffix: "",
    color: "a",
  },
  fear: {
    name: "Fear",
    nameLore: "Fear",
    nameShort: "Fear",
    nameTiny: "Fr",
    symbol: "☠",
    suffix: "",
    color: "a",
  },
  /* 
    name: "",
    nameLore: "",
    nameShort: "",
    nameTiny: "",
    symbol: "",
    suffix: "",
    color: "",
  */
};

module.exports = { symbols };
