module.exports = {
    talisman_upgrades: {
        WOLF_TALISMAN: ['WOLF_RING'],
        RING_POTION_AFFINITY: ['ARTIFACT_POTION_AFFINITY'],
        POTION_AFFINITY_TALISMAN: ['RING_POTION_AFFINITY', 'ARTIFACT_POTION_AFFINITY'],
        FEATHER_RING: ['FEATHER_ARTIFACT'],
        FEATHER_TALISMAN: ['FEATHER_RING', 'FEATHER_ARTIFACT'],
        SEA_CREATURE_RING: ['SEA_CREATURE_ARTIFACT'],
        SEA_CREATURE_TALISMAN: ['SEA_CREATURE_RING', 'SEA_CREATURE_ARTIFACT'],
        HEALING_TALISMAN: ['HEALING_RING'],
        CANDY_ARTIFACT: ['CANDY_RELIC'],
        CANDY_RING: ['CANDY_ARTIFACT', 'CANDY_RELIC'],
        CANDY_TALISMAN: ['CANDY_RING', 'CANDY_ARTIFACT', 'CANDY_RELIC'],
        INTIMIDATION_RING: ['INTIMIDATION_ARTIFACT'],
        INTIMIDATION_TALISMAN: ['INTIMIDATION_RING', 'INTIMIDATION_ARTIFACT'],
        SPIDER_RING: ['SPIDER_ARTIFACT'],
        SPIDER_TALISMAN: ['SPIDER_RING', 'SPIDER_ARTIFACT'],
        RED_CLAW_RING: ['RED_CLAW_ARTIFACT'],
        RED_CLAW_TALISMAN: ['RED_CLAW_RING', 'RED_CLAW_ARTIFACT'],
        HUNTER_TALISMAN: ['HUNTER_RING'],
        ZOMBIE_RING: ['ZOMBIE_ARTIFACT'],
        ZOMBIE_TALISMAN: ['ZOMBIE_RING', 'ZOMBIE_ARTIFACT'],
        BAT_RING: ['BAT_ARTIFACT'],
        BAT_TALISMAN: ['BAT_RING', 'BAT_ARTIFACT'],
        BROKEN_PIGGY_BANK: ['CRACKED_PIGGY_BANK', 'PIGGY_BANK'],
        CRACKED_PIGGY_BANK: ['PIGGY_BANK'],
        SPEED_TALISMAN: ['SPEED_RING', 'SPEED_ARTIFACT'],
        SPEED_RING: ['SPEED_ARTIFACT'],
        PERSONAL_COMPACTOR_4000: ['PERSONAL_COMPACTOR_5000', 'PERSONAL_COMPACTOR_6000', 'PERSONAL_COMPACTOR_7000'],
        PERSONAL_COMPACTOR_5000: ['PERSONAL_COMPACTOR_6000', 'PERSONAL_COMPACTOR_7000'],
        PERSONAL_COMPACTOR_6000: ['PERSONAL_COMPACTOR_7000'],
        PERSONAL_DELETOR_4000: ['PERSONAL_DELETOR_5000', 'PERSONAL_DELETOR_6000', 'PERSONAL_DELETOR_7000'],
        PERSONAL_DELETOR_5000: ['PERSONAL_DELETOR_6000', 'PERSONAL_DELETOR_7000'],
        PERSONAL_DELETOR_6000: ['PERSONAL_DELETOR_7000'],
        SCARF_STUDIES: ['SCARF_THESIS', 'SCARF_GRIMOIRE'],
        SCARF_THESIS: ['SCARF_GRIMOIRE'],
        CAT_TALISMAN: ['LYNX_TALISMAN', 'CHEETAH_TALISMAN'],
        LYNX_TALISMAN: ['CHEETAH_TALISMAN'],
        SHADY_RING: ['CROOKED_ARTIFACT', 'SEAL_OF_THE_FAMILY'],
        CROOKED_ARTIFACT: ['SEAL_OF_THE_FAMILY'],
        TREASURE_TALISMAN: ['TREASURE_RING', 'TREASURE_ARTIFACT'],
        TREASURE_RING: ['TREASURE_ARTIFACT'],
        BEASTMASTER_CREST_COMMON: ['BEASTMASTER_CREST_UNCOMMON', 'BEASTMASTER_CREST_RARE', 'BEASTMASTER_CREST_EPIC', 'BEASTMASTER_CREST_LEGENDARY'],
        BEASTMASTER_CREST_UNCOMMON: ['BEASTMASTER_CREST_RARE', 'BEASTMASTER_CREST_EPIC', 'BEASTMASTER_CREST_LEGENDARY'],
        BEASTMASTER_CREST_RARE: ['BEASTMASTER_CREST_EPIC', 'BEASTMASTER_CREST_LEGENDARY'],
        BEASTMASTER_CREST_EPIC: ['BEASTMASTER_CREST_LEGENDARY'],
        RAGGEDY_SHARK_TOOTH_NECKLACE: ['DULL_SHARK_TOOTH_NECKLACE', 'HONED_SHARK_TOOTH_NECKLACE', 'SHARP_SHARK_TOOTH_NECKLACE', 'RAZOR_SHARP_SHARK_TOOTH_NECKLACE'],
        DULL_SHARK_TOOTH_NECKLACE: ['HONED_SHARK_TOOTH_NECKLACE', 'SHARP_SHARK_TOOTH_NECKLACE', 'RAZOR_SHARP_SHARK_TOOTH_NECKLACE'],
        HONED_SHARK_TOOTH_NECKLACE: ['SHARP_SHARK_TOOTH_NECKLACE', 'RAZOR_SHARP_SHARK_TOOTH_NECKLACE'],
        SHARP_SHARK_TOOTH_NECKLACE: ['RAZOR_SHARP_SHARK_TOOTH_NECKLACE'],
        BAT_PERSON_TALISMAN: ['BAT_PERSON_RING', 'BAT_PERSON_ARTIFACT'],
        BAT_PERSON_RING: ['BAT_PERSON_ARTIFACT'],
        LUCKY_HOOF: ['ETERNAL_HOOF'],
        WITHER_ARTIFACT: ['WITHER_RELIC'],
        WEDDING_RING_0: ['WEDDING_RING_2', 'WEDDING_RING_4', 'WEDDING_RING_7', 'WEDDING_RING_9'],
        WEDDING_RING_2: ['WEDDING_RING_4', 'WEDDING_RING_7', 'WEDDING_RING_9'],
        WEDDING_RING_4: ['WEDDING_RING_7', 'WEDDING_RING_9'],
        WEDDING_RING_7: ['WEDDING_RING_9'],
        CAMPFIRE_TALISMAN_1: ['CAMPFIRE_TALISMAN_4', 'CAMPFIRE_TALISMAN_8', 'CAMPFIRE_TALISMAN_13', 'CAMPFIRE_TALISMAN_21'],
        CAMPFIRE_TALISMAN_4: ['CAMPFIRE_TALISMAN_8', 'CAMPFIRE_TALISMAN_13', 'CAMPFIRE_TALISMAN_21'],
        CAMPFIRE_TALISMAN_8: ['CAMPFIRE_TALISMAN_13', 'CAMPFIRE_TALISMAN_21'],
        CAMPFIRE_TALISMAN_13: ['CAMPFIRE_TALISMAN_21'],
        JERRY_TALISMAN_GREEN: ['JERRY_TALISMAN_BLUE', 'JERRY_TALISMAN_PURPLE', 'JERRY_TALISMAN_GOLDEN'],
        JERRY_TALISMAN_BLUE: ['JERRY_TALISMAN_PURPLE', 'JERRY_TALISMAN_GOLDEN'],
        JERRY_TALISMAN_PURPLE: ['JERRY_TALISMAN_GOLDEN'],
        TITANIUM_TALISMAN: ['TITANIUM_RING', 'TITANIUM_ARTIFACT', 'TITANIUM_RELIC'],
        TITANIUM_RING: ['TITANIUM_ARTIFACT', 'TITANIUM_RELIC'],
        TITANIUM_ARTIFACT: ['TITANIUM_RELIC'],
        BAIT_RING: ['SPIKED_ATROCITY'],
        MASTER_SKULL_TIER_1: ['MASTER_SKULL_TIER_2', 'MASTER_SKULL_TIER_3', 'MASTER_SKULL_TIER_4', 'MASTER_SKULL_TIER_5', 'MASTER_SKULL_TIER_6', 'MASTER_SKULL_TIER_7'],
        MASTER_SKULL_TIER_2: ['MASTER_SKULL_TIER_3', 'MASTER_SKULL_TIER_4', 'MASTER_SKULL_TIER_5', 'MASTER_SKULL_TIER_6', 'MASTER_SKULL_TIER_7'],
        MASTER_SKULL_TIER_3: ['MASTER_SKULL_TIER_4', 'MASTER_SKULL_TIER_5', 'MASTER_SKULL_TIER_6', 'MASTER_SKULL_TIER_7'],
        MASTER_SKULL_TIER_4: ['MASTER_SKULL_TIER_5', 'MASTER_SKULL_TIER_6', 'MASTER_SKULL_TIER_7'],
        MASTER_SKULL_TIER_5: ['MASTER_SKULL_TIER_6', 'MASTER_SKULL_TIER_7'],
        MASTER_SKULL_TIER_6: ['MASTER_SKULL_TIER_7'],
        SOULFLOW_PILE: ['SOULFLOW_BATTERY', 'SOULFLOW_SUPERCELL'],
        SOULFLOW_BATTERY: ['SOULFLOW_SUPERCELL'],
        ENDER_ARTIFACT: ['ENDER_RELIC'],
        POWER_TALISMAN: ['POWER_RING', 'POWER_ARTIFACT'],
        POWER_RING: ['POWER_ARTIFACT'],
        BINGO_TALISMAN: ['BINGO_RING'],
        BURNING_KUUDRA_CORE: ['FIERY_KUUDRA_CORE', 'INFERNA_KUUDRA_CORE'],
        FIERY_KUUDRA_CORE: ['INFERNA_KUUDRA_CORE'],
        BURSTSTOPPER_TALISMAN: ['BURSTSTOPPER_ARTIFACT'],
        ODGERS_BRONZE_TOOTH: ['ODGERS_SILVER_TOOTH', 'ODGERS_GOLD_TOOTH', 'ODGERS_DIAMOND_TOOTH'],
        ODGERS_SILVER_TOOTH: ['ODGERS_GOLD_TOOTH', 'ODGERS_DIAMOND_TOOTH'],
        ODGERS_GOLD_TOOTH: ['ODGERS_DIAMOND_TOOTH'],
    },

    talisman_duplicates: {
        WEDDING_RING_0: ['WEDDING_RING_1'],
        WEDDING_RING_2: ['WEDDING_RING_3'],
        WEDDING_RING_4: ['WEDDING_RING_5', 'WEDDING_RING_6'],
        WEDDING_RING_7: ['WEDDING_RING_8'],

        CAMPFIRE_TALISMAN_1: ['CAMPFIRE_TALISMAN_2', 'CAMPFIRE_TALISMAN_3'],
        CAMPFIRE_TALISMAN_4: ['CAMPFIRE_TALISMAN_5', 'CAMPFIRE_TALISMAN_6', 'CAMPFIRE_TALISMAN_7'],
        CAMPFIRE_TALISMAN_8: ['CAMPFIRE_TALISMAN_9', 'CAMPFIRE_TALISMAN_10', 'CAMPFIRE_TALISMAN_11', 'CAMPFIRE_TALISMAN_12'],
        CAMPFIRE_TALISMAN_13: ['CAMPFIRE_TALISMAN_14', 'CAMPFIRE_TALISMAN_15', 'CAMPFIRE_TALISMAN_16', 'CAMPFIRE_TALISMAN_17', 'CAMPFIRE_TALISMAN_18', 'CAMPFIRE_TALISMAN_19', 'CAMPFIRE_TALISMAN_20'],
        CAMPFIRE_TALISMAN_21: [
            'CAMPFIRE_TALISMAN_22',
            'CAMPFIRE_TALISMAN_23',
            'CAMPFIRE_TALISMAN_24',
            'CAMPFIRE_TALISMAN_25',
            'CAMPFIRE_TALISMAN_26',
            'CAMPFIRE_TALISMAN_27',
            'CAMPFIRE_TALISMAN_28',
            'CAMPFIRE_TALISMAN_29',
        ],
    },

    talismans: {
        WEDDING_RING_0: { name: 'Shiny Yellow Rock', rarity: 'common' },
        WEDDING_RING_2: { name: 'Mediocre Ring of Love', rarity: 'uncommon' },
        WEDDING_RING_4: { name: 'Modest Ring of Love', rarity: 'rare' },
        WEDDING_RING_7: { name: 'Exquisite Ring of Love', rarity: 'epic' },
        WEDDING_RING_9: { name: 'Legendary Ring of Love', rarity: 'legendary' },

        CAMPFIRE_TALISMAN_1: { name: 'Campfire Initiate Badge', rarity: 'common' },
        CAMPFIRE_TALISMAN_4: { name: 'Campfire Adept Badge', rarity: 'uncommon' },
        CAMPFIRE_TALISMAN_8: { name: 'Campfire Cultist Badge', rarity: 'rare' },
        CAMPFIRE_TALISMAN_13: { name: 'Campfire Scion Badge', rarity: 'epic' },
        CAMPFIRE_TALISMAN_21: { name: 'Campfire God Badge', rarity: 'legendary' },
        FARMING_TALISMAN: { name: 'Farming Talisman', rarity: 'common' },
        VACCINE_TALISMAN: { name: 'Vaccine Talisman', rarity: 'common' },
        WOOD_TALISMAN: { name: 'Wood Affinity Talisman', rarity: 'uncommon' },
        SKELETON_TALISMAN: { name: 'Skeleton Talisman', rarity: 'common' },
        COIN_TALISMAN: { name: 'Talisman of Coins', rarity: 'common' },
        MAGNETIC_TALISMAN: { name: 'Magnetic Talisman', rarity: 'uncommon' },
        GRAVITY_TALISMAN: { name: 'Gravity Talisman', rarity: 'uncommon' },
        VILLAGE_TALISMAN: { name: 'Village Affinity Talisman', rarity: 'common' },
        MINE_TALISMAN: { name: 'Mine Affinity Talisman', rarity: 'common' },
        NIGHT_VISION_CHARM: { name: 'Night Vision Charm', rarity: 'common' },
        LAVA_TALISMAN: { name: 'Lava Talisman', rarity: 'uncommon' },
        SCAVENGER_TALISMAN: { name: 'Scavenger Talisman', rarity: 'common' },
        FIRE_TALISMAN: { name: 'Fire Talisman', rarity: 'common' },
        PIGS_FOOT: { name: "Pig's Foot", rarity: 'rare' },
        WOLF_PAW: { name: 'Wolf Paw', rarity: 'uncommon' },
        FROZEN_CHICKEN: { name: 'Frozen Chicken', rarity: 'rare' },
        FISH_AFFINITY_TALISMAN: { name: 'Fish Affinity Talisman', rarity: 'rare' },
        FARMER_ORB: { name: 'Farmer Orb', rarity: 'uncommon' },
        HASTE_RING: { name: 'Haste Ring', rarity: 'rare' },
        EXPERIENCE_ARTIFACT: { name: 'Experience Artifact', rarity: 'epic' },
        NEW_YEAR_CAKE_BAG: { name: 'New Year Cake Bag', rarity: 'uncommon' },
        DAY_CRYSTAL: { name: 'Day Crystal', rarity: 'rare' },
        NIGHT_CRYSTAL: { name: 'Night Crystal', rarity: 'rare' },
        FEATHER_TALISMAN: { name: 'Feather Talisman', rarity: 'common' },
        FEATHER_RING: { name: 'Feather Ring', rarity: 'uncommon' },
        FEATHER_ARTIFACT: { name: 'Feather Artifact', rarity: 'rare' },
        POTION_AFFINITY_TALISMAN: { name: 'Potion Affinity Talisman', rarity: 'common' },
        RING_POTION_AFFINITY: { name: 'Potion Affinity Ring', rarity: 'uncommon' },
        ARTIFACT_POTION_AFFINITY: { name: 'Potion Affinity Artifact', rarity: 'rare' },
        HEALING_TALISMAN: { name: 'Healing Talisman', rarity: 'common' },
        HEALING_RING: { name: 'Healing Ring', rarity: 'uncommon' },
        CANDY_TALISMAN: { name: 'Candy Talisman', rarity: 'uncommon' },
        CANDY_RING: { name: 'Candy Ring', rarity: 'rare' },
        CANDY_ARTIFACT: { name: 'Candy Artifact', rarity: 'epic' },
        MELODY_HAIR: { name: "Melody's Hair", rarity: 'epic' },
        SEA_CREATURE_TALISMAN: { name: 'Sea Creature Talisman', rarity: 'common' },
        SEA_CREATURE_RING: { name: 'Sea Creature Ring', rarity: 'uncommon' },
        SEA_CREATURE_ARTIFACT: { name: 'Sea Creature Artifact', rarity: 'rare' },
        INTIMIDATION_TALISMAN: { name: 'Intimidation Talisman', rarity: 'common' },
        INTIMIDATION_RING: { name: 'Intimidation Ring', rarity: 'uncommon' },
        INTIMIDATION_ARTIFACT: { name: 'Intimidation Artifact', rarity: 'rare' },
        WOLF_TALISMAN: { name: 'Wolf Talisman', rarity: 'common' },
        WOLF_RING: { name: 'Wolf Ring', rarity: 'rare' },
        BAT_TALISMAN: { name: 'Bat Talisman', rarity: 'rare' },
        BAT_RING: { name: 'Bat Ring', rarity: 'epic' },
        BAT_ARTIFACT: { name: 'Bat Artifact', rarity: 'Legendary' },
        DEVOUR_RING: { name: 'Devour Ring', rarity: 'rare' },
        ZOMBIE_TALISMAN: { name: 'Zombie Talisman', rarity: 'common' },
        ZOMBIE_RING: { name: 'Zombie Ring', rarity: 'uncommon' },
        ZOMBIE_ARTIFACT: { name: 'Zombie Artifact', rarity: 'rare' },
        SPIDER_TALISMAN: { name: 'Spider Talisman', rarity: 'uncommon' },
        SPIDER_RING: { name: 'Spider Ring', rarity: 'rare' },
        SPIDER_ARTIFACT: { name: 'Spider Artifact', rarity: 'epic' },
        TARANTULA_TALISMAN: { name: 'Tarantula Talisman', rarity: 'epic' },
        SURVIVOR_CUBE: { name: 'Survivor Cube', rarity: 'rare' },
        WITHER_ARTIFACT: { name: 'Wither Artifact', rarity: 'epic' },
        RED_CLAW_TALISMAN: { name: 'Red Claw Talisman', rarity: 'uncommon' },
        RED_CLAW_RING: { name: 'Red Claw Ring', rarity: 'rare' },
        RED_CLAW_ARTIFACT: { name: 'Red Claw Artifact', rarity: 'epic' },
        SHADY_RING: { name: 'Shady Ring', rarity: 'uncommon' },
        CROOKED_ARTIFACT: { name: 'Crooked Artifact', rarity: 'rare' },
        SEAL_OF_THE_FAMILY: { name: 'Seal of the Family', rarity: 'epic' },
        PARTY_HAT_CRAB: { name: 'Crab Hat of Celebration - 2020', rarity: 'special' },
        PARTY_HAT_CRAB_ANIMATED: { name: 'Crab Hat of Celebration - 2022', rarity: 'special' },
        POTATO_TALISMAN: { name: 'Potato Talisman', rarity: 'common' },
        EMERALD_RING: { name: 'Emerald Ring', rarity: 'uncommon' },
        PERSONAL_COMPACTOR_4000: { name: 'Personal Compactor 4000', rarity: 'uncommon' },
        PERSONAL_COMPACTOR_5000: { name: 'Personal Compactor 5000', rarity: 'rare' },
        PERSONAL_COMPACTOR_6000: { name: 'Personal Compactor 6000', rarity: 'epic' },
        PERSONAL_COMPACTOR_7000: { name: 'Personal Compactor 7000', rarity: 'legendary' },
        PERSONAL_DELETOR_4000: { name: 'Personal Deletor 4000', rarity: 'uncommon' },
        PERSONAL_DELETOR_5000: { name: 'Personal Deletor 5000', rarity: 'rare' },
        PERSONAL_DELETOR_6000: { name: 'Personal Deletor 6000', rarity: 'epic' },
        PERSONAL_DELETOR_7000: { name: 'Personal Deletor 7000', rarity: 'legendary' },
        SPEED_TALISMAN: { name: 'Speed Talisman', rarity: 'common' },
        SPEED_RING: { name: 'Speed Ring', rarity: 'uncommon' },
        SPEED_ARTIFACT: { name: 'Speed Artifact', rarity: 'rare' },
        CAT_TALISMAN: { name: 'Cat Talisman', rarity: 'uncommon' },
        LYNX_TALISMAN: { name: 'Lynx Talisman', rarity: 'rare' },
        CHEETAH_TALISMAN: { name: 'Cheetah Talisman', rarity: 'epic' },
        SCARF_STUDIES: { name: "Scarf's Studies", rarity: 'rare' },
        SCARF_THESIS: { name: "Scarf's Thesis", rarity: 'epic' },
        SCARF_GRIMOIRE: { name: "Scarf's Grimoire", rarity: 'legendary' },
        TREASURE_TALISMAN: { name: 'Treasure Talisman', rarity: 'rare' },
        TREASURE_RING: { name: 'Treasure Ring', rarity: 'epic' },
        TREASURE_ARTIFACT: { name: 'Treasure Artifact', rarity: 'legendary' },
        MINERAL_TALISMAN: { name: 'Mineral Talisman', rarity: 'rare' },
        BEASTMASTER_CREST_COMMON: { name: 'Beastmaster Crest', rarity: 'common' },
        BEASTMASTER_CREST_UNCOMMON: { name: 'Beastmaster Crest', rarity: 'uncommon' },
        BEASTMASTER_CREST_RARE: { name: 'Beastmaster Crest', rarity: 'rare' },
        BEASTMASTER_CREST_EPIC: { name: 'Beastmaster Crest', rarity: 'epic' },
        BEASTMASTER_CREST_LEGENDARY: { name: 'Beastmaster Crest', rarity: 'legendary' },
        RAGGEDY_SHARK_TOOTH_NECKLACE: { name: 'Raggedy Shark Tooth Necklace', rarity: 'common' },
        DULL_SHARK_TOOTH_NECKLACE: { name: 'Dull Shark Tooth Necklace', rarity: 'uncommon' },
        HONED_SHARK_TOOTH_NECKLACE: { name: 'Honed Shark Tooth Necklace', rarity: 'rare' },
        SHARP_SHARK_TOOTH_NECKLACE: { name: 'Sharp Shark Tooth Necklace', rarity: 'epic' },
        RAZOR_SHARP_SHARK_TOOTH_NECKLACE: { name: 'Razor Sharp Shark Tooth Necklace', rarity: 'legendary' },
        HEGEMONY_ARTIFACT: { name: 'Hegemony Artifact', rarity: 'legendary' },
        BITS_TALISMAN: { name: 'Bits Talisman', rarity: 'rare' },
        BAT_PERSON_TALISMAN: { name: 'Bat Person Talisman', rarity: 'common' },
        BAT_PERSON_RING: { name: 'Bat Person Ring', rarity: 'uncommon' },
        BAT_PERSON_ARTIFACT: { name: 'Bat Person Artifact', rarity: 'rare' },
        CANDY_RELIC: { name: 'Candy Relic', rarity: 'legendary' },
        LUCKY_HOOF: { name: 'Lucky Hoof', rarity: 'uncommon' },
        WITHER_RELIC: { name: 'Wither Relic', rarity: 'legendary' },
        CATACOMBS_EXPERT_RING: { name: 'Catacombs Expert Ring', rarity: 'epic' },
        AUTO_RECOMBOBULATOR: { name: 'Auto Recombobulator', rarity: 'legendary' },
        JERRY_TALISMAN_GOLDEN: { name: 'Golden Jerry Artifact', rarity: 'legendary' },
        JERRY_TALISMAN_PURPLE: { name: 'Purple Jerry Talisman', rarity: 'epic' },
        JERRY_TALISMAN_BLUE: { name: 'Blue Jerry Talisman', rarity: 'rare' },
        JERRY_TALISMAN_GREEN: { name: 'Green Jerry Talisman', rarity: 'uncommon' },
        KING_TALISMAN: { name: 'King Talisman', rarity: 'common' },
        TITANIUM_TALISMAN: { name: 'Titanium Talisman', rarity: 'uncommon' },
        TITANIUM_RING: { name: 'Titanium Ring', rarity: 'rare' },
        TITANIUM_ARTIFACT: { name: 'Titanium Artifact', rarity: 'epic' },
        TITANIUM_RELIC: { name: 'Titanium Relic', rarity: 'legendary' },
        REAPER_ORB: { name: 'Reaper Orb', rarity: 'legendary' },
        DANTE_TALISMAN: { name: 'Dante Talisman', rarity: 'common' },
        PIGGY_BANK: { name: 'Piggy Bank', rarity: 'uncommon' },
        ENDER_ARTIFACT: { name: 'Ender Artifact', rarity: 'epic' },
        BAIT_RING: { name: 'Bait Ring', rarity: 'rare' },
        HUNTER_TALISMAN: { name: 'Hunter Talisman', rarity: 'uncommon' },
        HUNTER_RING: { name: 'Hunter Ring', rarity: 'rare' },
        ETERNAL_HOOF: { name: 'Eternal Hoof', rarity: 'rare' },
        BLOOD_GOD_CREST: { name: 'Blood God Crest', rarity: 'common' },
        SPIKED_ATROCITY: { name: 'Spiked Atrocity', rarity: 'epic' },
        MASTER_SKULL_TIER_1: { name: 'Master Skull - Tier 1', rarity: 'common' },
        MASTER_SKULL_TIER_2: { name: 'Master Skull - Tier 2', rarity: 'common' },
        MASTER_SKULL_TIER_3: { name: 'Master Skull - Tier 3', rarity: 'uncommon' },
        MASTER_SKULL_TIER_4: { name: 'Master Skull - Tier 4', rarity: 'uncommon' },
        MASTER_SKULL_TIER_5: { name: 'Master Skull - Tier 5', rarity: 'rare' },
        MASTER_SKULL_TIER_6: { name: 'Master Skull - Tier 6', rarity: 'epic' },
        MASTER_SKULL_TIER_7: { name: 'Master Skull - Tier 7', rarity: 'legendary' },
        SOULFLOW_PILE: { name: 'Soulflow Pile', rarity: 'uncommon' },
        SOULFLOW_BATTERY: { name: 'Soulflow Battery', rarity: 'rare' },
        SOULFLOW_SUPERCELL: { name: 'Soulflow Supercell', rarity: 'epic' },
        POCKET_ESPRESSO_MACHINE: { name: 'Pocket Espresso Machine', rarity: 'common' },
        HANDY_BLOOD_CHALICE: { name: 'Handy Blood Chalice', rarity: 'common' },
        ENDER_RELIC: { name: 'Ender Relic', rarity: 'legendary' },
        JUNGLE_AMULET: { name: 'Jungle Amulet', rarity: 'uncommon' },
        POWER_TALISMAN: { name: 'Talisman of Power', rarity: 'common' },
        POWER_RING: { name: 'Ring of Power', rarity: 'uncommon' },
        POWER_ARTIFACT: { name: 'Artifact of Power', rarity: 'rare' },
        NETHER_ARTIFACT: { name: 'Nether Artifact', rarity: 'epic' },
        BINGO_TALISMAN: { name: 'Bingo Talisman', rarity: 'common' },
        BINGO_RING: { name: 'Bingo Ring', rarity: 'uncommon' },
        BURSTSTOPPER_TALISMAN: { name: 'Burststopper Talisman', rarity: 'rare' },
        BURSTSTOPPER_ARTIFACT: { name: 'Burststopper Artifact', rarity: 'epic' },
        FIERY_KUUDRA_CORE: { name: 'Fiery Kuudra Core', rarity: 'epic' },
        BURNING_KUUDRA_CORE: { name: 'Burning Kuudra Core', rarity: 'rare' },
        INFERNAL_KUUDRA_CORE: { name: 'Infernal Kuudra Core', rarity: 'rare' },
        JACOBUS_REGISTER: { name: 'Jacobus Register', rarity: 'legendary' },
        ODGERS_BRONZE_TOOTH: { name: "Odger's Bronze Tooth", rarity: 'common' },
        ODGERS_SILVER_TOOTH: { name: "Odger's Silver Tooth", rarity: 'uncommon' },
        ODGERS_GOLD_TOOTH: { name: "Odger's Gold Tooth", rarity: 'rare' },
        ODGERS_DIAMOND_TOOTH: { name: "Odger's Diamond Tooth", rarity: 'epic' },
        PULSE_RING: { name: 'Pulse Ring', rarity: 'uncommon' },
        BLAZE_TALISMAN: { name: 'Blaze Talisman', rarity: 'rare' },
        NETHERRACK_LOOKING_SUNSHADE: { name: 'Netherrack-Looking Sunshade', rarity: 'common' },
    },
    max_upgrade_talismans: {
        WEDDING_RING_9: { name: 'Legendary Ring of Love', rarity: 'legendary' },
        CAMPFIRE_TALISMAN_21: { name: 'Campfire God Badge', rarity: 'legendary' },
        FARMING_TALISMAN: { name: 'Farming Talisman', rarity: 'common' },
        VACCINE_TALISMAN: { name: 'Vaccine Talisman', rarity: 'common' },
        WOOD_TALISMAN: { name: 'Wood Affinity Talisman', rarity: 'uncommon' },
        SKELETON_TALISMAN: { name: 'Skeleton Talisman', rarity: 'common' },
        COIN_TALISMAN: { name: 'Talisman of Coins', rarity: 'common' },
        MAGNETIC_TALISMAN: { name: 'Magnetic Talisman', rarity: 'uncommon' },
        GRAVITY_TALISMAN: { name: 'Gravity Talisman', rarity: 'uncommon' },
        VILLAGE_TALISMAN: { name: 'Village Affinity Talisman', rarity: 'common' },
        MINE_TALISMAN: { name: 'Mine Affinity Talisman', rarity: 'common' },
        NIGHT_VISION_CHARM: { name: 'Night Vision Charm', rarity: 'common' },
        LAVA_TALISMAN: { name: 'Lava Talisman', rarity: 'uncommon' },
        SCAVENGER_TALISMAN: { name: 'Scavenger Talisman', rarity: 'common' },
        PIGS_FOOT: { name: "Pig's Foot", rarity: 'rare' },
        WOLF_PAW: { name: 'Wolf Paw', rarity: 'uncommon' },
        FROZEN_CHICKEN: { name: 'Frozen Chicken', rarity: 'rare' },
        FISH_AFFINITY_TALISMAN: { name: 'Fish Affinity Talisman', rarity: 'rare' },
        FARMER_ORB: { name: 'Farmer Orb', rarity: 'uncommon' },
        HASTE_RING: { name: 'Haste Ring', rarity: 'rare' },
        EXPERIENCE_ARTIFACT: { name: 'Experience Artifact', rarity: 'epic' },
        NEW_YEAR_CAKE_BAG: { name: 'New Year Cake Bag', rarity: 'uncommon' },
        DAY_CRYSTAL: { name: 'Day Crystal', rarity: 'rare' },
        NIGHT_CRYSTAL: { name: 'Night Crystal', rarity: 'rare' },
        FEATHER_ARTIFACT: { name: 'Feather Artifact', rarity: 'rare' },
        ARTIFACT_POTION_AFFINITY: { name: 'Potion Affinity Artifact', rarity: 'rare' },
        HEALING_RING: { name: 'Healing Ring', rarity: 'uncommon' },
        MELODY_HAIR: { name: "Melody's Hair", rarity: 'epic' },
        SEA_CREATURE_ARTIFACT: { name: 'Sea Creature Artifact', rarity: 'rare' },
        INTIMIDATION_ARTIFACT: { name: 'Intimidation Artifact', rarity: 'rare' },
        WOLF_RING: { name: 'Wolf Ring', rarity: 'rare' },
        BAT_ARTIFACT: { name: 'Bat Artifact', rarity: 'Legendary' },
        DEVOUR_RING: { name: 'Devour Ring', rarity: 'rare' },
        ZOMBIE_ARTIFACT: { name: 'Zombie Artifact', rarity: 'rare' },
        SPIDER_ARTIFACT: { name: 'Spider Artifact', rarity: 'epic' },
        TARANTULA_TALISMAN: { name: 'Tarantula Talisman', rarity: 'epic' },
        SURVIVOR_CUBE: { name: 'Survivor Cube', rarity: 'rare' },
        RED_CLAW_ARTIFACT: { name: 'Red Claw Artifact', rarity: 'epic' },
        SEAL_OF_THE_FAMILY: { name: 'Seal of the Family', rarity: 'epic' },
        PARTY_HAT_CRAB: { name: 'Crab Hat of Celebration - 2020', rarity: 'special' },
        PARTY_HAT_CRAB_ANIMATED: { name: 'Crab Hat of Celebration - 2022', rarity: 'special' },
        POTATO_TALISMAN: { name: 'Potato Talisman', rarity: 'common' },
        EMERALD_RING: { name: 'Emerald Ring', rarity: 'uncommon' },
        PERSONAL_COMPACTOR_7000: { name: 'Personal Compactor 7000', rarity: 'legendary' },
        PERSONAL_DELETOR_7000: { name: 'Personal Deletor 7000', rarity: 'legendary' },
        SPEED_ARTIFACT: { name: 'Speed Artifact', rarity: 'rare' },
        CHEETAH_TALISMAN: { name: 'Cheetah Talisman', rarity: 'epic' },
        SCARF_GRIMOIRE: { name: "Scarf's Grimoire", rarity: 'legendary' },
        TREASURE_ARTIFACT: { name: 'Treasure Artifact', rarity: 'legendary' },
        MINERAL_TALISMAN: { name: 'Mineral Talisman', rarity: 'rare' },
        BEASTMASTER_CREST_LEGENDARY: { name: 'Beastmaster Crest', rarity: 'legendary' },
        RAZOR_SHARP_SHARK_TOOTH_NECKLACE: { name: 'Razor Sharp Shark Tooth Necklace', rarity: 'legendary' },
        HEGEMONY_ARTIFACT: { name: 'Hegemony Artifact', rarity: 'legendary' },
        BITS_TALISMAN: { name: 'Bits Talisman', rarity: 'rare' },
        BAT_PERSON_ARTIFACT: { name: 'Bat Person Artifact', rarity: 'rare' },
        CANDY_RELIC: { name: 'Candy Relic', rarity: 'legendary' },
        WITHER_RELIC: { name: 'Wither Relic', rarity: 'epic' },
        CATACOMBS_EXPERT_RING: { name: 'Catacombs Expert Ring', rarity: 'epic' },
        AUTO_RECOMBOBULATOR: { name: 'Auto Recombobulator', rarity: 'legendary' },
        JERRY_TALISMAN_GOLDEN: { name: 'Golden Jerry Artifact', rarity: 'legendary' },
        KING_TALISMAN: { name: 'King Talisman', rarity: 'common' },
        TITANIUM_RELIC: { name: 'Titanium Relic', rarity: 'legendary' },
        REAPER_ORB: { name: 'Reaper Orb', rarity: 'legendary' },
        DANTE_TALISMAN: { name: 'Dante Talisman', rarity: 'common' },
        PIGGY_BANK: { name: 'Piggy Bank', rarity: 'uncommon' },
        HUNTER_RING: { name: 'Hunter Ring', rarity: 'rare' },
        ETERNAL_HOOF: { name: 'Eternal Hoof', rarity: 'rare' },
        BLOOD_GOD_CREST: { name: 'Blood God Crest', rarity: 'common' },
        SPIKED_ATROCITY: { name: 'Spiked Atrocity', rarity: 'epic' },
        MASTER_SKULL_TIER_7: { name: 'Master Skull - Tier 7', rarity: 'legendary' },
        SOULFLOW_SUPERCELL: { name: 'Soulflow Supercell', rarity: 'epic' },
        POCKET_ESPRESSO_MACHINE: { name: 'Pocket Espresso Machine', rarity: 'common' },
        HANDY_BLOOD_CHALICE: { name: 'Handy Blood Chalice', rarity: 'common' },
        ENDER_RELIC: { name: 'Ender Relic', rarity: 'legendary' },
        JUNGLE_AMULET: { name: 'Jungle Amulet', rarity: 'uncommon' },
        POWER_ARTIFACT: { name: 'Artifact of Power', rarity: 'rare' },
        NETHER_ARTIFACT: { name: 'Nether Artifact', rarity: 'epic' },
        BINGO_RING: { name: 'Bingo Ring', rarity: 'uncommon' },
        BURSTSTOPPER_ARTIFACT: { name: 'Burststopper Artifact', rarity: 'epic' },
        INFERNAL_KUUDRA_CORE: { name: 'Infernal Kuudra Core', rarity: 'rare' },
        JACOBUS_REGISTER: { name: 'Jacobus Register', rarity: 'legendary' },
        ODGERS_DIAMOND_TOOTH: { name: "Odger's Diamond Tooth", rarity: 'epic' },
        PULSE_RING: { name: 'Pulse Ring', rarity: 'uncommon' },
        BLAZE_TALISMAN: { name: 'Blaze Talisman', rarity: 'rare' },
        NETHERRACK_LOOKING_SUNSHADE: { name: 'Netherrack-Looking Sunshade', rarity: 'common' },
    },
};
