module.exports = [
    'zombie commander whip',
    'dreadlord sword',
    'silent death',
    'zombie knight sword',
    'zombie soldier cutlass',
    'skeleton lord helmet',
    'earth shard',
    'conjuring',
    'parkour start/end',
    'pillar quartz block',
    'chiseled quartz block',
    'plumber\'s sponge',
    'oak wood',
    'sludge juice',
    'wishing compass',
    'rune',
    'inflatable jerry',
    'spirit leap',
    'mini sandcastle',
    'decoy',
    "arachne's keeperfragment",
    'hypixel sandcastle',
    'red goblin egg',
    'worm membrane',
    'soul string',
    'tasty cheese'
]
