module.exports = [
    'bane of athropods 1',
    'bane of athropods 2',
    'bane of athropods 3',
    'bane of athropods 4',
    'bane of athropods 5',
    'cleave 1',
    'cleave 2',
    'cleave 3',
    'cleave 4',
    'cleave 5',
    'critical 1',
    'critical 2',
    'critical 3',
    'critical 4',
    'critical 5',
    'cubism 1',
    'cubism 2',
    'cubism 3',
    'cubism 4',
    'cubism 5',
    'ender slayer 1',
    'ender slayer 2',
    'ender slayer 3',
    'ender slayer 4',
    'ender slayer 5',
    'execute 1',
    'execute 2',
    'execute 3',
    'execute 4',
    'execute 5',
    'experience 1',
    'experience 2',
    'experience 3',
    'fire aspect 1',
    'fire aspect 2',
    'first strike 1',
    'first strike 2',
    'first strike 3',
    'first strike 4',
    'giant killer 1',
    'giant killer 2',
    'giant killer 3',
    'giant killer 4',
    'giant killer 5',
    'impaling 1',
    'impaling 2',
    'impaling 3',
    'knockback 1',
    'knockback 2',
    'lethality 1',
    'lethality 2',
    'lethality 3',
    'lethality 4',
    'lethality 5',
    'life steal 1',
    'life steal 2',
    'life steal 3',
    'looting 1',
    'looting 2',
    'looting 3',
    'luck 1',
    'luck 2',
    'luck 3',
    'luck 4',
    'luck 5',
    'prosecute 1',
    'prosecute 2',
    'prosecute 3',
    'prosecute 4',
    'prosecute 5',
    'scavenger 1',
    'scavenger 2',
    'scavenger 3',
    'sharpness 1',
    'sharpness 2',
    'sharpness 3',
    'sharpness 4',
    'sharpness 5',
    'smite 1',
    'smite 2',
    'smite 3',
    'smite 4',
    'smite 5',
    'syphon 1',
    'syphon 2',
    'syphon 3',
    'telekinesis 1',
    'thunderbolt 1',
    'thunderbolt 2',
    'thunderbolt 3',
    'thunderbolt 4',
    'thunderbolt 5',
    'thunderlord 1',
    'thunderlord 2',
    'thunderlord 3',
    'thunderlord 4',
    'thunderlord 5',
    'titan killer 1',
    'titan killer 2',
    'titan killer 3',
    'titan killer 4',
    'titan killer 5',
    'triple-strike 1',
    'triple-strike 2',
    'triple-strike 3',
    'triple-strike 4',
    'triple-strike 5',
    'vampirism 1',
    'vampirism 2',
    'vampirism 3',
    'vampirism 4',
    'vampirism 5',
    'venomous 1',
    'venomous 2',
    'venomous 3',
    'venomous 4',
    'venomous 5',
    'aiming 1',
    'aiming 2',
    'aiming 3',
    'aiming 4',
    'aiming 5',
    'chance 1',
    'chance 2',
    'chance 3',
    'chance 4',
    'chance 5',
    'flame 1',
    'infinite quiver 1',
    'infinite quiver 2',
    'infinite quiver 3',
    'infinite quiver 4',
    'infinite quiver 5',
    'piercing 1',
    'power 1',
    'power 2',
    'power 3',
    'power 4',
    'power 5',
    'snipe 1',
    'snipe 2',
    'snipe 3',
    'punch 1',
    'punch 2',
    'aqua affinity 1',
    'blast protection 1',
    'blast protection 2',
    'blast protection 3',
    'blast protection 4',
    'blast protection 5',
    'depth strider 1',
    'depth strider 2',
    'depth strider 3',
    'feather falling 1',
    'feather falling 2',
    'feather falling 3',
    'feather falling 4',
    'feather falling 5',
    'fire protection 1',
    'fire protection 2',
    'fire protection 3',
    'fire protection 4',
    'fire protection 5',
    'frost walker 1',
    'frost walker 2',
    'growth 1',
    'growth 2',
    'growth 3',
    'growth 4',
    'growth 5',
    'projectile protection 1',
    'projectile protection 2',
    'projectile protection 3',
    'projectile protection 4',
    'projectile protection 5',
    'protection 1',
    'protection 2',
    'protection 3',
    'protection 4',
    'protection 5',
    'respiration 1',
    'respiration 2',
    'respiration 3',
    'thorns 1',
    'thorns 2',
    'thorns 3',
    'efficiency 1',
    'efficiency 2',
    'efficiency 3',
    'efficiency 4',
    'efficiency 5',
    'harvesting 1',
    'harvesting 2',
    'harvesting 3',
    'harvesting 4',
    'harvesting 5',
    'fortune 1',
    'fortune 2',
    'fortune 3',
    'rainbow 1',
    'silk touch 1',
    'smelting touch 1',
    'angler 1',
    'angler 2',
    'angler 3',
    'angler 4',
    'angler 5',
    'blessing 1',
    'blessing 2',
    'blessing 3',
    'blessing 4',
    'blessing 5',
    'caster 1',
    'caster 2',
    'caster 3',
    'caster 4',
    'caster 5',
    'frail 1',
    'frail 2',
    'frail 3',
    'frail 4',
    'frail 5',
    'luck of the sea 1',
    'luck of the sea 2',
    'luck of the sea 3',
    'luck of the sea 4',
    'luck of the sea 5',
    'lure 1',
    'lure 2',
    'lure 3',
    'lure 4',
    'lure 5',
    'magnet 1',
    'magnet 2',
    'magnet 3',
    'magnet 4',
    'magnet 5',
    'spiked hook 1',
    'spiked hook 2',
    'spiked hook 3',
    'spiked hook 4',
    'spiked hook 5',
    'luck 6',
    'scavenger 4',
    'scavenger 5',
    'smite 6',
    'syphon 4',
    'infinite quiver 6',
    'infinite quiver 7',
    'infinite quiver 8',
    'infinite quiver 9',
    'blast protection 6',
    'blast protection 7',
    'projectile protection 6',
    'projectile protection 7',
    'feather falling 6',
    'feather falling 7',
    'feather falling 8',
    'feather falling 9',
    'fire protection 6',
    'fire protection 7',
    'angler 6',
    'caster 6',
    'frail 6',
    'luck of the sea 6',
    'lure 6',
    'magnet 6',
    'spiked hook 6'
]