module.exports = [
    "allium",
    "anvil",
    "apple",
    "armor stand",
    "arrow",
    "arrow of fire resistance",
    "arrow of healing",
    "arrow of invisibility",
    "arrow of leaping",
    "arrow of night vision",
    "arrow of poison",
    "arrow of regeneration",
    "arrow of slowness",
    "arrow of strength",
    "arrow of swiftness",
    "arrow of water breathing",
    "arrow of weakness",
    "awkward potion",
    "azure bluet",
    "baked potato",
    "beacon",
    "bed",
    "beetroot",
    "beetroot seeds",
    "beetroot soup",
    "blaze powder",
    "blaze rod",
    "block of redstone",
    "blue orchid",
    "boat",
    "bone",
    "bone meal",
    "book",
    "book and quill",
    "bottle of enchanting",
    "bow",
    "bowl",
    "bread",
    "brewing stand",
    "brown mushroom",
    "bucket",
    "cactus",
    "cactus green dye",
    "cake",
    "carrot",
    "carrot on a stick",
    "cauldron",
    "chainmail boots",
    "chainmail chestplate",
    "chainmail helmet",
    "chainmail leggings",
    "charcoal",
    "chest",
    "chorus fruit",
    "clay",
    "clay brick",
    "coal",
    "cocoa bean",
    "cocoa plant",
    "command block",
    "compass",
    "cooked chicken",
    "cooked fish",
    "cooked mutton",
    "cooked porkchop",
    "cooked rabbit",
    "cookie",
    "cyan dye",
    "dandelion",
    "dandelion yellow dye",
    "daylight sensor",
    "dead shrub",
    "diamond axe",
    "diamond boots",
    "diamond chestplate",
    "diamond gem",
    "diamond helmet",
    "diamond hoe",
    "diamond horse armor",
    "diamond leggings",
    "diamond pickaxe",
    "diamond shovel",
    "diamond sword",
    "dispenser",
    "double tallgrass",
    "dragon egg",
    "dragon's breath",
    "dropper",
    "egg",
    "elytra",
    "emerald",
    "empty map",
    "enchanted book",
    "enchanted golden apple",
    "enchantment table",
    "end crystal",
    "end gateway",
    "ender chest",
    "ender pearl",
    "exploration map",
    "eye of ender",
    "feather",
    "fermented spider eye",
    "fire charge",
    "firework rocket",
    "firework star",
    "cont.",
    "fishing rod",
    "flint",
    "flint and steel",
    "flower pot",
    "furnace",
    "ghast tear",
    "glass bottle",
    "glowstone dust",
    "gold axe",
    "gold boots",
    "gold chestplate",
    "gold helmet",
    "gold hoe",
    "gold horse armor",
    "gold ingot",
    "gold leggings",
    "gold nugget",
    "gold pickaxe",
    "gold shovel",
    "gold sword",
    "golden apple",
    "golden carrot",
    "gray dye",
    "gunpowder",
    "harming potion",
    "harming potion ii",
    "harming splash",
    "harming splash ii",
    "healing potion",
    "healing potion ii",
    "healing splash",
    "healing splash ii",
    "hopper",
    "ink sack",
    "iron axe",
    "iron boots",
    "iron chestplate",
    "iron door",
    "iron helmet",
    "iron hoe",
    "iron horse armor",
    "iron ingot",
    "iron leggings",
    "iron pickaxe",
    "iron shovel",
    "iron sword",
    "iron trapdoor",
    "item frame",
    "jukebox",
    "ladder",
    "lapis lazuli",
    "large fern",
    "lead",
    "leather",
    "leather boots",
    "leather chestplate",
    "leather helmet",
    "leather leggings",
    "lever",
    "light blue dye",
    "light gray dye",
    "lilac",
    "lime dye",
    "locked chest",
    "magenta dye",
    "magma block",
    "magma cream",
    "melon seeds",
    "minecart",
    "mundane potion",
    "mushroom stew",
    "name tag",
    "nether quartz",
    "nether star",
    "nether wart",
    "nether wart seeds",
    "note block",
    "observer",
    "orange dye",
    "orange tulip",
    "oxeye daisy",
    "painting",
    "paper",
    "peony",
    "pink dye",
    "pink tulip",
    "piston",
    "cont.",
    "poisonous potato",
    "poppy",
    "potato",
    "prismarine crystals",
    "prismarine shard",
    "pumpkin pie",
    "pumpkin seeds",
    "purple dye",
    "purpur stairs",
    "quartz stairs",
    "rabbit hide",
    "rabbit stew",
    "rabbit's foot",
    "rail",
    "raw beef",
    "raw chicken",
    "raw fish",
    "raw mutton",
    "raw porkchop",
    "raw rabbit",
    "red mushroom",
    "red tulip",
    "redstone comparator",
    "redstone dust",
    "redstone lamp",
    "redstone repeater",
    "redstone torch",
    "redstone wire",
    "rose bush",
    "rose red dye",
    "rotten flesh",
    "saddle",
    "sea lantern",
    "shears",
    "shield",
    "shulker shell",
    "sign",
    "slime ball",
    "snowball",
    "spider eye",
    "steak",
    "stick",
    "sticky piston",
    "stone axe",
    "stone hoe",
    "stone pickaxe",
    "stone pressure plate",
    "stone shovel",
    "stone sword",
    "string",
    "sugar",
    "sugar cane",
    "sunflower",
    "tnt",
    "tall grass",
    "thick potion",
    "torch",
    "totem of undying",
    "trapdoor",
    "trapped chest",
    "tripwire",
    "tripwire hook",
    "watch",
    "water bottle",
    "wet sponge",
    "wheat",
    "wheat seeds",
    "white tulip",
    "wooden axe",
    "wooden door",
    "wooden hoe",
    "wooden pickaxe",
    "wooden pressure plate",
    "wooden shovel",
    "wooden sword",
    "workbench",
    "written book",
    "air",
    "andesite",
    "barrier",
    "bedrock",
    "birch-wood slab",
    "black wool",
    "block of coal",
    "block of diamond",
    "block of emerald",
    "block of gold",
    "block of iron",
    "blue wool",
    "bone block",
    "bookshelf",
    "brick",
    "brick slab",
    "brick stairs",
    "brown wool",
    "chorus flower",
    "chorus plant",
    "clay block",
    "coal ore",
    "cobblestone",
    "cobblestone slab",
    "cobblestone stairs",
    "cobblestone wall",
    "cobweb",
    "cyan wool",
    "dark prismarine",
    "diamond ore",
    "diorite",
    "dirt",
    "emerald ore",
    "end portal",
    "end portal frame",
    "end stone",
    "end stone bricks",
    "end rod",
    "farmland",
    "fire",
    "glass",
    "glass pane",
    "glowstone",
    "gold ore",
    "granite",
    "grass",
    "cont.",
    "grass path",
    "gravel",
    "gray wool",
    "green wool",
    "hardened clay",
    "hay bale",
    "ice",
    "iron bars",
    "iron ore",
    "jack-o-lantern",
    "jungle-wood slab",
    "lapis lazuli block",
    "lapis lazuli ore",
    "lava",
    "light blue wool",
    "light gray wool",
    "lily pad",
    "lime wool",
    "magenta wool",
    "melon vine",
    "mob spawner",
    "moss stone",
    "mossy cobblestone wall",
    "mycelium",
    "nether brick",
    "nether brick fence",
    "nether brick slab",
    "nether brick stairs",
    "nether quartz ore",
    "netherrack",
    "oak-wood slab",
    "obsidian",
    "orange wool",
    "packed ice",
    "pink wool",
    "podzol",
    "polished andesite",
    "polished diorite",
    "polished granite",
    "portal",
    "prismarine",
    "cont.",
    "prismarine bricks",
    "pumpkin",
    "pumpkin vine",
    "purple wool",
    "purpur block",
    "purpur pillar",
    "purpur slab",
    "quartz block",
    "quartz slab",
    "red sandstone",
    "red sandstone slab",
    "red sandstone stairs",
    "red wool",
    "redstone ore",
    "sand",
    "sandstone",
    "sandstone slab",
    "sandstone stairs",
    "slime block",
    "snow",
    "snow block",
    "soul sand",
    "sponge",
    "spruce-wood slab",
    "stone",
    "stone brick slab",
    "stone brick stairs",
    "stone bricks",
    "stone slab",
    "structure block",
    "vines",
    "water",
    "wooden slab",
    "wool",
    "yellow wool",
]